### ISSUE TITLE
Add hook that triggers when all component properties are set

### ISSUE THREAD

**Issue by nicolocarpignoli** [Chialab/dna#38]
At the moment there is no hook in the life cycle of a component that is triggered when all properties are set to a value. 

Assuming a dev has to make actions that required all properties setted: actually the only thing possible is to check for every properties' value on every `on<PropertyName>changedCallback`, or doing something similiar in the callback of `observe` of every single property. This can be tricky and can lead to more code to mantain and more complexity.

This is a proposal of adding a new hook, something like `propertiesSetCallback`, in which a developer can do things with the security of have all properties set to the value passed at the creation of the component.
The most useful use cases are when such properties are passed to the component via `jsx`.

I'd like to start a discussion if I mislead something about life cycle or anything. If it's a good proposal I'd be glad to help with an eventual PR.

**Comment by edoardocavazza** [comment]
in the `connectedCallback`, after the `super` call, you are in the situation you had described ;)
