### ISSUE TITLE
[RESOLVED] Reactive Component Example does not work.

### ISSUE THREAD

**Issue by LePichu** [chialab/dna#97]
The reactive component example from the website does not seem to work, for context, this one specifically: 
```ts
import { Component, customElement, html, property, listen } from 'https://esm.sh/@chialab/dna@3.21.3';

@customElement('hello-world')
export class HelloWorld extends Component {
  // define an observable property
  @property() name = '';

  render() {
    return html`
      <h1>Hello ${this.name || 'World'}!</h1>
      <input
        name="firstName"
        placeholder="Type your name"
        value="${this.name}"
      />
    `;
  }

  // listen input changes
  @listen('input', 'input[name="firstName"]')
  protected onInputChange(event: Event, target: HTMLInputElement) {
    this.name = target.value;
  }
}
```
# Expectation/Result:
The name should reanimate using the new one from the input bar, however, it doesn't.

# Environment
- OS: Windows
- Platform: Deno
- Build Tool: ESBuild

**Comment by LePichu** [comment]
This is the output ESBuild produces: https://hastebin.com/tasuwobeja.js
This is the code building it:
```ts
import * as esbuild from "https://deno.land/x/esbuild@v0.15.12/mod.js"
import { httpImports } from "https://deno.land/x/esbuild_plugin_http_imports@v1.2.4/index.ts"

await esbuild.build({
    entryPoints: [
        `main.tsx`
    ],
    bundle: true,
    loader: {
        ".ts": "ts",
        ".js": "js",
        ".html": "text"
    },
    outfile: "main.js",
    platform: "browser",
    format: "esm",
    target: "esnext",
    plugins: [
        {
            name: "close-on-complete",
            setup(build) {
                build.onEnd((result) => {
                    console.log("Finished Building!")
                    Deno.exit(result.errors.length >= 1 ? 1 : 0)
                })
            }
        },
        httpImports({
            defaultToJavascriptIfNothingElseFound: true
        })
    ],
    jsxFactory: "h",
    jsxFragment: "Fragment"
})
```

**Comment by LePichu** [comment]
Update: Built it with Node.js as core runtime platform, same ESBuild configuration, seems so that doesn't work either. Is it recommended to use Vite instead?

**Comment by LePichu** [comment]
Did some more digging, tried using the Vanilla JS Example with the DNA Dependency from a URL, this does not work either:
```js
import { Component, customElements, html, property, listen } from '@chialab/dna';

class HelloWorld extends Component {
    static get properties() {
        return {
            // define an observed property
            name: {
                type: String,
                defaultValue: '',
            },
        };
    }

    static get listeners() {
        return {
            // delegate an event
            'change input[name="firstName"]': function(event, target) {
                this.name = target.value;
            }
        };
    }

    render() {
        return html`
            <input name="firstName" value="${this.name}" />
            <h1>Hello ${this.name || 'World'}!</h1>
        `;
    }
}

customElements.define('hello-world', HelloWorld);
```

**Comment by edoardocavazza** [comment]
Hi @LePichu, thanks for reporting!

DNA should be bundler/devserver agnostic, we also use esbuild as primary bundler.

Can you share your `tsconfig.json` please?

**Comment by LePichu** [comment]
> Hi @LePichu, thanks for reporting!
> 
> DNA should be bundler/devserver agnostic, we also use esbuild as primary bundler.
> 
> Can you share your `tsconfig.json` please?
Under Deno: 
```json
{
    "tasks": {
        "build": "deno run -A build.ts"
    },
    "compilerOptions": {
        "lib": [
            "deno.window",
            "./files.d.ts"
        ],
        "jsxFactory": "h",
        "jsxFragmentFactory": "Fragment"
    },
    "importMap": "import_map.json"
}
```
Under Node:
```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "jsxFactory": "h",
        "jsxFragmentFactory": "Fragment"
    }
}
```

By the way you might not have noticed that I updated my previous commit, it definitely works with the vanilla example in browser directly but not when bundled via ESBuild.

**Comment by edoardocavazza** [comment]
When using the `esnext` target, esbuild will match typescript behavior to define decorated property through `Object.defineProperty`, which is not currently supported.

Try to add this conf to `compilerOptions` in `tsconfig.json`:

```
"useDefineForClassFields": false
```

**Comment by LePichu** [comment]
@edoardocavazza Thank you very much, it works now. Looking forward to using DNA for a project of mine.

**Comment by edoardocavazza** [comment]
Thank you @LePichu! Please share any feedback!

**Comment by LePichu** [comment]
> Thank you @LePichu! Please share any feedback!

Is there a Discord server for discussing DNA-related things?

**Comment by edoardocavazza** [comment]
We have not a Discord server (but we are considering to), you can use GitHub discussions in the meanwhile.
